### ISSUE TITLE
The roof holes aren't symetrical ine the stl file.

### ISSUE THREAD

**Issue by cozytom** [dheera/shoji-lamps#1]
The roof holes are 71mm x 65mm outside to outside.

the base holes are 71mmx71mm outside to outside.

FYI

**Comment by NiyaShy** [comment]
Haven't built a lamp yet, but according to the description photos and what I can see in the STL, that's fully intended. 
On the roof, the Z bars slide into place outwards in opposite directions for locking, increasing their spacing in that direction. 
For the base, all bars slide in the same direction (keeping their spacing) and get locked with pins.

**Comment by dheera** [comment]
Yep, this is intentional as @NiyaShy explained.
The base uses the pin lock to allow easy access to whatever lighting circuitry you put on it; the entire rest of the lamp (besides the base) is intended to stay permanently together and will conveniently come off in one piece if you remove the base pins.
